ci fix

diff --git a/megamcib/ubuntu/precise/postinst b/megamcib/ubuntu/precise/postinst
--- a/megamcib/ubuntu/precise/postinst
+++ b/megamcib/ubuntu/precise/postinst
@@ -1,35 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
-cat > //etc/init/megamanalytics.conf <<EOF
-#!upstart
-description "node.js server"
-author      "Megam Systems"
+mkdir -p /var/lib/megam/megamcib
 
-start on startup
-stop on shutdown
+set -e
 
-script
-    export HOME="/root"
+. /usr/share/debconf/confmodule
 
-    echo $$ > /var/run/megam/megamanalytics/megamanalytics.pid
-    exec sudo /usr/bin/node /usr/share/megam/megamanalytics/tap_monitor.js >> /var/log/megam/megamanalytics/megamanalytics.log 2>&1
-end script
+chown megam:megam /var/run/megam/megamcib
 
-pre-start script
-    # Date format same as (new Date()).toISOString() for consistency
-    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamanalytics/megamanalytics.log
-end script
+chown megam:megam /var/log/megam/megamcib
 
-pre-stop script
-    rm /var/run/megam/megamanalytics/megamanalytics.pid
-    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamanalytics/megamanalytics.log
-end script
-EOF
+initctl reload-configuration
 
+service megamcib start || echo "megamcib could not be started. Try manually with service megamcib start"
 
+db_settitle megamcib/cibt
 
-echo "starting megamanalytics"
-sudo start megamanalytics
-echo "started"
+db_input critical megamcib/cibt || true
+db_go
 
-
+db_fset megamcib/cibt seen false
