swarm docker cluster scheduler fix.

diff --git a/megamswarm/nix/postinst b/megamswarm/nix/postinst
--- a/megamswarm/nix/postinst
+++ b/megamswarm/nix/postinst
@@ -1,11 +1,22 @@
 #!/bin/bash
 
-mkdir -p /var/lib/megam/megamd
+# we create a cluster token and set it in BMDK_CLUSTERID
+bmdkcluster() {
+mkdir -p /var/lib/megam/megamswarm
+bmdk_clusterid = `/usr/share/megam/megamswarm/bin/swarm create`
 
-initctl reload-configuration
+echo "BMDK_CLUSTERID " $bmdk_clusterid  >> /var/log/upstart/megamd.log
 
-getip(){
-while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
+#set MEGAM_BMDK_CLUSTERID for megamswarm
+cat > /var/lib/megam/env.sh <<EOF
+initctl set-env MEGAM_BMDK_CLUSTERID=$bmdk_clusterid
+EOF
+
+}
+
+# Grab the hostip and set it in BMDK_CLUSTERIP
+grab_hostip() {
+  while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
 		[ "$Mask" = "00000000" ] && \
 		interface="$Iface" && \
 		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
@@ -13,17 +24,18 @@ while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRT
 		ipaddr=${ipaddr%%/*} && \
 		break
 	done < /proc/net/route
+  initctl set-env MEGAM_BMDK_CLUSTERIP=$ipaddr
 }
-getip
 
-cat > //var/lib/megam/env.sh <<EOF
-initctl set-env ETCD_ADDR="$ipaddr:4001"
-initctl set-env ETCD_BIND_ADDR="$ipaddr:4001"
-initctl set-env ETCD_PEER_ADDR="$ipaddr:7001"
-initctl set-env ETCD_PEER_BIND_ADDR="$ipaddr:7001"
-EOF
+# Start docker in dtached mode and join the ip address in the cluster
+join_bmdkcluster() {
+  docker -H tcp://0.0.0.0:2375 -d
+  /usr/share/megam/megamswarm/bin/swarm join --addr=$ipaddr token://$bmdk_custerid
+}
 
-chmod 755 /var/lib/megam/env.sh
+cron_and_bmdkcluster
+grab_hostip
+join_bmdkcluster
 
-
-service megamd start || echo "megamd could not be started. Try manually with service megamd start"
+## voila start the service now (swarm manage)
+service megamswarm start || echo "megamswarm could not be started. Try manually with service megamswarm start"
